# Site settings
title: Emily Laflamme
email: emily.laflamme@gmail.com
description: Hello!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emlaflamme.github.io" # the base hostname & protocol for your site
twitter_username: emily_laflamme
github_username:  emlaflamme
paginate: 5
theme-dark: false #Set to true to change to dark website theme

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
